### ISSUE TITLE
Admin - record actual time of pickup and delivery

### ISSUE THREAD

**Issue by ghost** [KnightHawk3/packr#31] opened 2016-08-11 21:17 UTC
As an admin I should be able to record the actual time of pick up and delivery

**Comment by DayeHorse3** [comment] 2016-08-18 00:16
Acceptance Criteria
The admin should be able to record actual time of pickup

**Comment by ZeroEcks** [comment] 2016-08-19 01:43
Duplicate of #9?

**Closed as completed** 2016-08-24 23:12 UTC
Labels: duplicate, user stories, Must have
